// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"


namespace WarriorGameplayTags
{
	/** Input Tags **/
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipKatana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipKatana);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipBow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipBow);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipScabbard);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipScabbard);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Aiming);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_ArrowFire);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_Rage);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Katana_Light);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Katana_Heavy);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Katana_Third);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Bow_Light);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Bow_Heavy);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Bow_Third);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PickUp_Heal);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_InterAction_Grace);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_InterAction_BossRoom);


	

	/** Player Tags **/
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Scabbard);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Bow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Quiver);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Bow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Bow);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Third_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Bow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Bow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Third_Bow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Rage);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_PickUp_Heal);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Aiming);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_ArrowFire);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_InterAction_Grace);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipKatana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquipKatana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipBow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquipBow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ActivateRage);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_AOE);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ConsumeHeal);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_InterAction_Grace);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_InterAction_BossRoom);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_CounterAttack);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Activating);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Active);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Full);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_None);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Aiming);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Equipped_Katana);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Equipped_Bow);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Charging);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_ArrowReady);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_ArrowFire);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_SuperArmor);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Arrow);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Katana_Light);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Katana_Heavy);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Katana_Third);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Bow_Light);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Bow_Heavy);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Bow_Third);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Roll);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Guard);

	/** Enemy Tags **/
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemies);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemiesEverySecond);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SpawnHealingItem);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Meteor);
	
	

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Unblockable);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Size_Small);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Size_Medium);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Size_Large);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_UI_Rampage_BossBar);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_UI_Sevarog_BossBar);

	/** Shared Tags **/
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_JustGuardHitReact);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);


	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible);
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Slow);

	/** Game Data tags **/
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_MainMenuMap)
	PROJECTP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_GameplayMap)

}